vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        suite_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
